storage: filesystem
storage_option:
  base_path: ./
  region: aws-region
  bucket: aws-bucket
  access_key: aws-access-key-id
  access_secret: aws-secret-access-key
  client_id: google-client-id
  client_secret: google-client-secret
  client_token: google-client-token
  dropbox_token: dropbox-token